/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Modelo.*;
import Modelo.FinanzasAPI;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FinanzasGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanzasGUI.class.getName());

    /**
     * Creates new form FinanzasGUI
     */
    public FinanzasGUI() {

        initComponents();
        FinanzasAPI.cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        botonGastoHormiga = new javax.swing.JButton();
        botonGastoNecesario = new javax.swing.JButton();
        botonIngreso = new javax.swing.JButton();
        botonVerGastos = new javax.swing.JButton();
        botonVerIngresos = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre ");

        campoNombre.setText("campoNombre");
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor");

        campoValor.setText("campoValor");

        botonGastoHormiga.setText("Agregar Gasto Hormiga");
        botonGastoHormiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGastoHormigaActionPerformed(evt);
            }
        });

        botonGastoNecesario.setText("Agregar Gasto Necesario");
        botonGastoNecesario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGastoNecesarioActionPerformed(evt);
            }
        });

        botonIngreso.setText("Agregar Ingreso");
        botonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoActionPerformed(evt);
            }
        });

        botonVerGastos.setText("Ver Gastos Ordenados");
        botonVerGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerGastosActionPerformed(evt);
            }
        });

        botonVerIngresos.setText("Ver Ingresos Ordenados");
        botonVerIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerIngresosActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar gasto/ingreso");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonVerIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerGastos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGastoHormiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGastoNecesario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGastoHormiga)
                    .addComponent(botonIngreso))
                .addGap(18, 18, 18)
                .addComponent(botonGastoNecesario)
                .addGap(35, 35, 35)
                .addComponent(botonVerGastos)
                .addGap(18, 18, 18)
                .addComponent(botonVerIngresos)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        String nombre = campoNombre.getText();
        int valor = Integer.parseInt(campoValor.getText());
        boolean esFijo = false;
        FinanzasAPI.registrarGasto(nombre, valor, esFijo);
    }//GEN-LAST:event_campoNombreActionPerformed

    private void botonGastoHormigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGastoHormigaActionPerformed
        try {
            String nombre = campoNombre.getText();
            int valor = Integer.parseInt(campoValor.getText());

            FinanzasAPI.registrarGasto(nombre, valor,true);

            JOptionPane.showMessageDialog(this, "Gasto hormiga agregado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: verifica los datos.");
        }
    }//GEN-LAST:event_botonGastoHormigaActionPerformed

    private void botonGastoNecesarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGastoNecesarioActionPerformed
        try {
            String nombre = campoNombre.getText();
            int valor = Integer.parseInt(campoValor.getText());

            FinanzasAPI.registrarGasto(nombre, valor,false);

            JOptionPane.showMessageDialog(this, "Gasto necesario agregado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: verifica los datos.");
        }
    }//GEN-LAST:event_botonGastoNecesarioActionPerformed

    private void botonVerGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerGastosActionPerformed
        StringBuilder sb = new StringBuilder("GASTOS ORDENADOS\n\n");
        ArrayList<Gasto> lista = new ArrayList<>(FinanzasAPI.getGastos());
        lista.sort((a, b) -> Integer.compare(a.getCosto(), b.getCosto()));

        for (Gasto g : lista) {
            sb.append(g.toString()).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_botonVerGastosActionPerformed

    private void botonVerIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerIngresosActionPerformed
        StringBuilder sb = new StringBuilder("INGRESOS ORDENADOS\n\n");
        ArrayList<Ingreso> lista = new ArrayList<>(FinanzasAPI.getIngresos());
        lista.sort((a, b) -> Integer.compare(a.getValor(), b.getValor()));

        for (Ingreso i : lista) {
            sb.append(i.toString()).append("\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_botonVerIngresosActionPerformed

    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        try {
            String nombre = campoNombre.getText();
            int valor = Integer.parseInt(campoValor.getText());

            FinanzasAPI.registrarIngreso(nombre, valor);

            JOptionPane.showMessageDialog(this, "Ingreso agregado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: verifica los datos.");
        }
    }//GEN-LAST:event_botonIngresoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        String[] opciones = {"Gasto", "Ingreso"};
        int tipo = JOptionPane.showOptionDialog(
                this,
                "¿Qué desea editar?",
                "Editar Registro",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (tipo == 0) {
            StringBuilder lista = new StringBuilder("LISTA DE GASTOS:\n\n");
            ArrayList<Gasto> gastos = new ArrayList<>(FinanzasAPI.getGastos());
            for (int i = 0; i < gastos.size(); i++) {
                lista.append(i).append(" -> ").append(gastos.get(i)).append("\n");
            }
            JOptionPane.showMessageDialog(this, lista);

            int index = Integer.parseInt(JOptionPane.showInputDialog("Digite el índice del gasto a editar:"));
            String nuevoNombre = JOptionPane.showInputDialog("Nuevo nombre:");
            int nuevoValor = Integer.parseInt(JOptionPane.showInputDialog("Nuevo valor:"));

            FinanzasAPI.actualizarGasto(index, nuevoNombre, nuevoValor);
            JOptionPane.showMessageDialog(this, "Gasto editado correctamente.");

        } else if (tipo == 1) {
            StringBuilder lista = new StringBuilder("LISTA DE INGRESOS:\n\n");
            ArrayList<Ingreso> ingresos = new ArrayList<>(FinanzasAPI.getIngresos());

            for (int i = 0; i < ingresos.size(); i++) {
                lista.append(i).append(" -> ").append(ingresos.get(i)).append("\n");
            }

            JOptionPane.showMessageDialog(this, lista);

            int index = Integer.parseInt(JOptionPane.showInputDialog("Digite el índice del ingreso a editar:"));
            String nuevoNombre = JOptionPane.showInputDialog("Nuevo nombre:");
            int nuevoValor = Integer.parseInt(JOptionPane.showInputDialog("Nuevo valor:"));

            FinanzasAPI.actualizarIngreso(index, nuevoNombre, nuevoValor);
            JOptionPane.showMessageDialog(this, "Ingreso editado correctamente.");
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinanzasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonGastoHormiga;
    private javax.swing.JButton botonGastoNecesario;
    private javax.swing.JButton botonIngreso;
    private javax.swing.JButton botonVerGastos;
    private javax.swing.JButton botonVerIngresos;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
